# Generated by Django 5.1.1 on 2024-10-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
