# Generated by Django 5.1.1 on 2024-10-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_email',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
